#!/usr/bin/env bash
# shellcheck disable=SC2312

# run the command `ln pre-commit .git/hooks/` from repo directory

echo "=> vscode-settings repository: pre-commit hook"

if git-diff-index -pM --cached HEAD |
	# new additions only
	rg '^+' |
	# grep for blocked strings
	rg -i 'apitoken'; then
	echo -e "\033[0;31m\nBlocking commit: a disallowed setting was found!\033[0m" >&2
	exit 1
fi
